-- ============================================================================
-- Time-Based Partitioning Setup
-- ============================================================================
-- This file contains partition management functions that are used by the
-- partitioning migration (20251126123346_enable_time_based_partitioning)
--
-- Partitioning Strategy:
-- - user_activities: Monthly partitions (12 months retention)
-- - system_metrics: Weekly partitions (8 weeks retention)
-- - audit_logs: Monthly partitions (12 months retention)
-- - optimization_statistics: Monthly partitions (12 months retention)
-- - suggestion_metrics: Monthly partitions (12 months retention)
--
-- Maintenance:
-- - Run create_future_partitions() monthly via cron job
-- - Use manage-partitions.sql for manual partition management
-- - Use partition-maintenance.ts script for automated maintenance
-- ============================================================================

-- Note: Actual partitioning is handled by migration:
-- backend/prisma/migrations/20251126123346_enable_time_based_partitioning/migration.sql
--
-- This file is kept for reference and contains the partition management
-- functions that are created during migration.

