/**
 * Cutting List Domain Entity
 *
 * Represents a cutting list with business logic
 *
 * @module domain/entities/CuttingList
 * @version 1.0.0
 */

import { WeekNumber } from "../valueObjects/WeekNumber";
import { CuttingListItem } from "./CuttingListItem";
import { CuttingListStatus } from "@prisma/client";

export interface CuttingListProps {
  readonly id: string;
  readonly name: string;
  readonly description?: string;
  readonly status: CuttingListStatus;
  readonly userId: string;
  readonly weekNumber?: WeekNumber | null;
  readonly metadata?: Record<string, unknown> | null;
  readonly sections?: Record<string, unknown> | null;
  readonly items?: CuttingListItem[];
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Cutting List Domain Entity
 */
export class CuttingList {
  private constructor(private readonly props: CuttingListProps) {
    this.validate();
  }

  /**
   * Create a new CuttingList
   */
  public static create(
    props: Omit<CuttingListProps, "id" | "createdAt" | "updatedAt" | "items">,
  ): CuttingList {
    return new CuttingList({
      ...props,
      id: "", // Will be generated by repository
      items: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  /**
   * Reconstruct from persistence
   */
  public static fromPersistence(props: CuttingListProps): CuttingList {
    return new CuttingList(props);
  }

  /**
   * Validate entity invariants
   */
  private validate(): void {
    if (!this.props.name || this.props.name.trim().length === 0) {
      throw new Error("CuttingList name is required");
    }
    if (this.props.name.length > 200) {
      throw new Error("CuttingList name must be 200 characters or less");
    }
    if (this.props.description && this.props.description.length > 1000) {
      throw new Error(
        "CuttingList description must be 1000 characters or less",
      );
    }
    if (!this.props.userId || this.props.userId.trim().length === 0) {
      throw new Error("CuttingList userId is required");
    }
  }

  // Getters
  public get id(): string {
    return this.props.id;
  }

  public get name(): string {
    return this.props.name;
  }

  public get description(): string | undefined {
    return this.props.description;
  }

  public get status(): CuttingListStatus {
    return this.props.status;
  }

  public get userId(): string {
    return this.props.userId;
  }

  public get weekNumber(): WeekNumber | null | undefined {
    return this.props.weekNumber;
  }

  public get metadata(): Record<string, unknown> | null | undefined {
    return this.props.metadata;
  }

  public get sections(): Record<string, unknown> | null | undefined {
    return this.props.sections;
  }

  public get items(): CuttingListItem[] {
    return this.props.items || [];
  }

  public get createdAt(): Date {
    return this.props.createdAt;
  }

  public get updatedAt(): Date {
    return this.props.updatedAt;
  }

  /**
   * Update name
   */
  public updateName(name: string): CuttingList {
    if (name.length > 200) {
      throw new Error("CuttingList name must be 200 characters or less");
    }
    return new CuttingList({
      ...this.props,
      name,
      updatedAt: new Date(),
    });
  }

  /**
   * Update description
   */
  public updateDescription(description: string | undefined): CuttingList {
    if (description && description.length > 1000) {
      throw new Error(
        "CuttingList description must be 1000 characters or less",
      );
    }
    return new CuttingList({
      ...this.props,
      description,
      updatedAt: new Date(),
    });
  }

  /**
   * Update status
   */
  public updateStatus(status: CuttingListStatus): CuttingList {
    return new CuttingList({
      ...this.props,
      status,
      updatedAt: new Date(),
    });
  }

  /**
   * Update week number
   */
  public updateWeekNumber(
    weekNumber: WeekNumber | null | undefined,
  ): CuttingList {
    return new CuttingList({
      ...this.props,
      weekNumber,
      updatedAt: new Date(),
    });
  }

  /**
   * Add item
   */
  public addItem(item: CuttingListItem): CuttingList {
    const items = [...(this.props.items || []), item];
    return new CuttingList({
      ...this.props,
      items,
      updatedAt: new Date(),
    });
  }

  /**
   * Remove item
   */
  public removeItem(itemId: string): CuttingList {
    const items = (this.props.items || []).filter((item) => item.id !== itemId);
    return new CuttingList({
      ...this.props,
      items,
      updatedAt: new Date(),
    });
  }

  /**
   * Update item
   */
  public updateItem(itemId: string, updatedItem: CuttingListItem): CuttingList {
    const items = (this.props.items || []).map((item) =>
      item.id === itemId ? updatedItem : item,
    );
    return new CuttingList({
      ...this.props,
      items,
      updatedAt: new Date(),
    });
  }

  /**
   * Get total items count
   */
  public getTotalItemsCount(): number {
    return this.props.items?.length || 0;
  }

  /**
   * Get total quantity
   */
  public getTotalQuantity(): number {
    return (
      this.props.items?.reduce(
        (sum, item) => sum + item.quantity.getValue(),
        0,
      ) || 0
    );
  }

  /**
   * Check if list is empty
   */
  public isEmpty(): boolean {
    return this.getTotalItemsCount() === 0;
  }

  /**
   * Check if list can be processed
   */
  public canBeProcessed(): boolean {
    return this.props.status === CuttingListStatus.READY && !this.isEmpty();
  }
}
