/**
 * Production Plan Domain Entity
 *
 * Represents a production plan with business logic
 *
 * @module domain/entities/ProductionPlan
 * @version 1.0.0
 */

import { WeekNumber } from "../valueObjects/WeekNumber";
import { ProductionPlanItem } from "./ProductionPlanItem";

export interface ProductionPlanProps {
  readonly id: string;
  readonly weekNumber: number;
  readonly year: number;
  readonly status: string;
  readonly uploadedBy?: string | null;
  readonly metadata?: Record<string, unknown> | null;
  readonly items?: ProductionPlanItem[];
  readonly uploadedAt: Date;
}

/**
 * Production Plan Domain Entity
 */
export class ProductionPlan {
  private constructor(private readonly props: ProductionPlanProps) {
    this.validate();
  }

  /**
   * Create a new ProductionPlan
   */
  public static create(
    props: Omit<ProductionPlanProps, "id" | "uploadedAt" | "items">,
  ): ProductionPlan {
    return new ProductionPlan({
      ...props,
      id: "", // Will be generated by repository
      items: [],
      uploadedAt: new Date(),
    });
  }

  /**
   * Reconstruct from persistence
   */
  public static fromPersistence(props: ProductionPlanProps): ProductionPlan {
    return new ProductionPlan(props);
  }

  /**
   * Validate entity invariants
   */
  private validate(): void {
    if (this.props.weekNumber < 1 || this.props.weekNumber > 53) {
      throw new Error("ProductionPlan weekNumber must be between 1 and 53");
    }
    if (this.props.year < 2000 || this.props.year > 2100) {
      throw new Error("ProductionPlan year must be between 2000 and 2100");
    }
    if (!this.props.status || this.props.status.trim().length === 0) {
      throw new Error("ProductionPlan status is required");
    }
    if (this.props.status.length > 50) {
      throw new Error("ProductionPlan status must be 50 characters or less");
    }
  }

  // Getters
  public get id(): string {
    return this.props.id;
  }

  public get weekNumber(): number {
    return this.props.weekNumber;
  }

  public get year(): number {
    return this.props.year;
  }

  public get status(): string {
    return this.props.status;
  }

  public get uploadedBy(): string | null | undefined {
    return this.props.uploadedBy;
  }

  public get metadata(): Record<string, unknown> | null | undefined {
    return this.props.metadata;
  }

  public get items(): ProductionPlanItem[] {
    return this.props.items || [];
  }

  public get uploadedAt(): Date {
    return this.props.uploadedAt;
  }

  /**
   * Update status
   */
  public updateStatus(status: string): ProductionPlan {
    if (status.length > 50) {
      throw new Error("ProductionPlan status must be 50 characters or less");
    }
    return new ProductionPlan({
      ...this.props,
      status,
    });
  }

  /**
   * Add item
   */
  public addItem(item: ProductionPlanItem): ProductionPlan {
    const items = [...(this.props.items || []), item];
    return new ProductionPlan({
      ...this.props,
      items,
    });
  }

  /**
   * Remove item
   */
  public removeItem(itemId: string): ProductionPlan {
    const items = (this.props.items || []).filter((item) => item.id !== itemId);
    return new ProductionPlan({
      ...this.props,
      items,
    });
  }

  /**
   * Get total items count
   */
  public getTotalItemsCount(): number {
    return this.props.items?.length || 0;
  }

  /**
   * Get total quantity
   */
  public getTotalQuantity(): number {
    return this.props.items?.reduce((sum, item) => sum + item.miktar, 0) || 0;
  }

  /**
   * Check if plan is empty
   */
  public isEmpty(): boolean {
    return this.getTotalItemsCount() === 0;
  }

  /**
   * Check if plan is active
   */
  public isActive(): boolean {
    return this.props.status === "active";
  }
}
